### ISSUE TITLE
Possible to add volume limiting for headphones and volume persistence?

### ISSUE THREAD

**Issue by espoelstra** [CircuitMess/CircuitMess-Ringo#41]
I tried using the 3.5mm port with my Sony headphones and even at the lowest volume just before muting the audio was uncomfortably loud. For the time being I can try using my Aumeo in between the phone and any headphones to add an external volume adjustment, but that isn't a great long term solution. I'd also worry that any children learning to solder or program with this device that are really excited to use it may damage their hearing if they play games or listen to music for long periods of time.

**Comment by robbie8-bit** [comment]
Hello,

Unfortunately, there are some limitations regarding headphone use, since we don't exactly know when the headphones are plugged in. This is a hardware issue and cannot be solved via software updates. We will try to fix it in some future versions of the phone.

Thank you for the support and for the suggestion!

Cheers,
Robert
